config/routes.rb
Rails.application.routes.draw do
root "books#top"
resources :books
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
validates :title, presence: true
validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  @books = Book.all
  @book = Book.new
  end
  
  def show
  @book = Book.find(params[:id])
  end
  
  def create
  @book = Book.new(book_params)
  if @book.save
    flash[:complete] = "Book was successfully created."
     redirect_to book_path(@book)
  else 
    @books = Book.all
    render :index
  end
  end
  
  def edit
  @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
  if @book.update(book_params)
    flash[:complete] = "Book was successfully created."
    redirect_to book_path(@book.id)
  else
   @books = Book.all
   render :edit
  end  
  end
  
  def destroy
    book = Book.find(params[:id])
    if book.destroy
    flash[:complete]="Book was successfully destroyed."
    redirect_to "/books"
    end
  end
  
   private
   def book_params
    params.require(:book).permit(:title, :body)
   end
   end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<% if flash[:complete] %>
  <div class="flash">
    <%= flash[:complete] %>
  </div>
<% end %>
<main class="edit-main">
  <h1>Editing Book</h1>
    <%= form_for(@book, url:"/books/#{@book.id}") do |f| %>
    <% if @book.errors.any? %>
      <div class="error">
        <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-title">Title</div>
      <%= f.text_field :title %>
    <div class="form-body">Body</div>
      <%= f.text_area :body %><br>
    <div class="upload">
      <%= f.submit " Update Book" %>
    </div>
  <% end %>
    <div class="menu">
      <%= link_to "Show", book_path(@book), class:"Editlink" %>
    </div>
      |
    <div class="menu">
      <%= link_to "Back", books_path, class:"Editlink" %>
    </div>
  </body>
</main>

app/views/books/index.html.erb
<% if flash[:complete] %>
  <div class="flash">
    <%= flash[:complete] %>
  </div>
<% end %>
<header>
  <h1 class="top">Books</h1>
</header>
<main class="index-main">
  <table cellspacing="10">
    <tr>
      <th>Title</th>
      <th>Body</th>
    </tr>
    <% @books.each do |book| %>
    <tr>
  	  <td><%= book.title %></td>
  	  <td><%= book.body %></td>
      <td><%= link_to "Show", book_path(book), class:"Editlink" %></td>
      <td><%= link_to "Edit", edit_book_path(book), class:"Editlink" %></td>
      <td><%= link_to "Destroy", book_path(book), method: :delete, data: {confirm: "Are you sure?"}, class:"Editlink" %></td>
    </tr>
  	<% end %>
  </table>
  <h2>New book</h2>
  <%= form_with model:@book, local:true do |f| %>
    <% if @book.errors.any? %>
      <div class="error">
        <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-title">Title</div>
      <%= f.text_field :title %>
    <div class="form-body">Body</div>
      <%= f.text_area :body %><br>
    <div class="upload">
      <%= f.submit " Create Book" %>
    </div>
  <% end %>
</main>

app/views/books/show.html.erb
<main class="show-main">
    <% if flash[:complete] %>
    <div class="flash">
     <%= flash[:complete] %>
        
    </div>
    <% end %>
     <table class="show-table" cellspacing="10">
    <tr>
      <td><b>Title:</b></td>
      <td><%= @book.title %></td>
    </tr>
    <tr>
  	  <td><b>Body:</b></td>
  	  <td><%= @book.body %></td>
    </tr>
  </table>
  <div class="menu">
    <%= link_to "Edit", edit_book_path(@book), class:"Editlink" %>
  </div>
   |
  <div class="menu">
    <%= link_to "Back", books_path, class:"Editlink" %>
  </div>
</main>

</main>

app/views/books/top.html.erb
<h1 class="top">ようこそ Bookersへ！</h1>
  <p class="top-text"><strong><b>Bookers</b></strong>では、さまざまな書籍に関するあなたの意見や<br>
  印象を共有し交換することができます
　</p>
<%= link_to "start", books_path, class:"start" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>